_core:
  default_config_hash: ZFSvo-iFbY7wmQJGLzHKHTQ8QrxsPohDjrIb9UAy8Yc
definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  entity__scheduled_update__collection_view__media_library__global_media_library_page:
    enabled: false
    menu_name: admin
    parent: system.admin_content
    expanded: false
    weight: 0
