_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  workflow_buttons: -1
  admin_toolbar: 0
  admin_toolbar_tools: 0
  anchor_link: 0
  automated_cron: 0
  basic_auth: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cas: 0
  checklistapi: 0
  ckeditor: 0
  coffee: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_update: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  custom_gin_override: 0
  cwru_default_academic_credentials: 0
  cwru_default_accordion: 0
  cwru_default_accordion_section: 0
  cwru_default_additional_job_descriptions: 0
  cwru_default_additional_view_orders: 0
  cwru_default_aside: 0
  cwru_default_award_honor: 0
  cwru_default_biography: 0
  cwru_default_biography_education: 0
  cwru_default_block_layout: 0
  cwru_default_button: 0
  cwru_default_cas_setting: 0
  cwru_default_centers: 0
  cwru_default_content: 0
  cwru_default_course_name: 0
  cwru_default_degree: 0
  cwru_default_departments: 0
  cwru_default_drupal_site: 0
  cwru_default_error_page: 0
  cwru_default_external_appointment: 0
  cwru_default_footer: 0
  cwru_default_gallery: 0
  cwru_default_gallery_section: 0
  cwru_default_hero_landing_page: 0
  cwru_default_hero_one_column: 0
  cwru_default_image_styles_for_cwru: 0
  cwru_default_job_title: 0
  cwru_default_job_title_affiliation: 0
  cwru_default_media_bundles: 0
  cwru_default_meta_field_storage: 0
  cwru_default_presentation: 0
  cwru_default_publication: 0
  cwru_default_residency: 0
  cwru_default_robust_3_column_page: 0
  cwru_default_roles: 0
  cwru_default_schools: 0
  cwru_default_site_affiliation: 0
  cwru_default_site_information: 0
  cwru_default_social: 0
  cwru_default_social_url_icon_section: 0
  cwru_default_subfeature: 0
  cwru_default_tab_section: 0
  cwru_default_tabs: 0
  cwru_default_text_editors_formats: 0
  cwru_default_user_roles: 0
  cwru_default_views_filters: 0
  cwru_default_workflows: 0
  datetime: 0
  dblog: 0
  diff: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_file: 0
  embed: 0
  encrypt: 0
  entity: 0
  entity_block: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  fakeobjects: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_url: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_iconpicker: 0
  gin_toolbar: 0
  help: 0
  history: 0
  ief_table_view_mode: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_resizable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  key: 0
  link: 0
  linkit: 0
  media: 0
  media_entity_generic: 0
  media_entity_instagram: 0
  media_entity_slideshow: 0
  media_entity_twitter: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  paragraphs_edit: 0
  path: 0
  path_alias: 0
  real_aes: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  responsive_image: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  slick: 0
  slick_paragraphs: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  viewfield: 0
  views_infinite_scroll: 0
  views_ui: 0
  workflows: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  yearonly: 0
  yoast_seo: 0
  pathauto: 1
  xmlsitemap: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  cms_content_sync: 50
  cms_content_sync_health: 99
  cms_content_sync_developer: 100
  cms_content_sync_views: 100
  cwrubaseconfigkit: 1000
theme:
  bootstrap: 0
  olivero: 0
  claro: 0
  crew: 0
  gin: 0
profile: cwrubaseconfigkit
