_core:
  default_config_hash: '-Rw1lJjHbrGpNzvmSlo_fQr9p_pmtwmgpts-JUhedvE'
favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/custom/crew/favicon.ico
  url: 'https://dudbm6bcnmy8e.cloudfront.net/cwru-drupal-assets/images/favicon.ico'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
cdn_provider: ''
schemas:
  bootstrap: 8000
  crew: 8000
breadcrumb_home: 1
region_wells:
  rave_region: ''
  pre_header: ''
  header: ''
  navigation: ''
  navigation_collapsible: ''
  breadcrumbs: ''
  highlighted: ''
  fluid_content: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table_responsive: '-1'
table: ''
breadcrumb_title: 0
footer_options:
  campus_location: campus_location
  social_media: 0
  secondary_footer: 0
department_header: ''
header_options:
  longer_site_title: 0
  button_right: 0
  hide_biographies: 0
  header_move_nav: 0
cdn_theme: ''
cdn_cache_ttl_versions: 0
cdn_cache_ttl_themes: 0
cdn_cache_ttl_assets: 0
cdn_cache_ttl_library: 0
reset: 'Reset Broken Cache'
apply: Apply
reset_http_request_cache: ''
department_header_url: ''
school_name: ''
school_url: ''
